/**
 * Comprehensive list of all countries for selection
 * Priority countries (our focus markets + USA) appear first, then alphabetically
 */

export interface CountryOption {
  id: string;
  name: string;
  priority: boolean;
}

// Priority countries (top 6)
const PRIORITY_COUNTRIES: CountryOption[] = [
  { id: 'armenia', name: 'Armenia', priority: true },
  { id: 'mongolia', name: 'Mongolia', priority: true },
  { id: 'turkiye', name: 'Türkiye', priority: true },
  { id: 'uzbekistan', name: 'Uzbekistan', priority: true },
  { id: 'vietnam', name: 'Vietnam', priority: true },
  { id: 'usa', name: 'United States', priority: true },
];

// All other countries (alphabetically)
const OTHER_COUNTRIES: CountryOption[] = [
  { id: 'afghanistan', name: 'Afghanistan', priority: false },
  { id: 'albania', name: 'Albania', priority: false },
  { id: 'algeria', name: 'Algeria', priority: false },
  { id: 'andorra', name: 'Andorra', priority: false },
  { id: 'angola', name: 'Angola', priority: false },
  { id: 'antigua_and_barbuda', name: 'Antigua and Barbuda', priority: false },
  { id: 'argentina', name: 'Argentina', priority: false },
  { id: 'australia', name: 'Australia', priority: false },
  { id: 'austria', name: 'Austria', priority: false },
  { id: 'azerbaijan', name: 'Azerbaijan', priority: false },
  { id: 'bahamas', name: 'Bahamas', priority: false },
  { id: 'bahrain', name: 'Bahrain', priority: false },
  { id: 'bangladesh', name: 'Bangladesh', priority: false },
  { id: 'barbados', name: 'Barbados', priority: false },
  { id: 'belarus', name: 'Belarus', priority: false },
  { id: 'belgium', name: 'Belgium', priority: false },
  { id: 'belize', name: 'Belize', priority: false },
  { id: 'benin', name: 'Benin', priority: false },
  { id: 'bhutan', name: 'Bhutan', priority: false },
  { id: 'bolivia', name: 'Bolivia', priority: false },
  { id: 'bosnia_and_herzegovina', name: 'Bosnia and Herzegovina', priority: false },
  { id: 'botswana', name: 'Botswana', priority: false },
  { id: 'brazil', name: 'Brazil', priority: false },
  { id: 'brunei', name: 'Brunei', priority: false },
  { id: 'bulgaria', name: 'Bulgaria', priority: false },
  { id: 'burkina_faso', name: 'Burkina Faso', priority: false },
  { id: 'burundi', name: 'Burundi', priority: false },
  { id: 'cambodia', name: 'Cambodia', priority: false },
  { id: 'cameroon', name: 'Cameroon', priority: false },
  { id: 'canada', name: 'Canada', priority: false },
  { id: 'cape_verde', name: 'Cape Verde', priority: false },
  { id: 'central_african_republic', name: 'Central African Republic', priority: false },
  { id: 'chad', name: 'Chad', priority: false },
  { id: 'chile', name: 'Chile', priority: false },
  { id: 'china', name: 'China', priority: false },
  { id: 'colombia', name: 'Colombia', priority: false },
  { id: 'comoros', name: 'Comoros', priority: false },
  { id: 'congo_brazzaville', name: 'Congo (Brazzaville)', priority: false },
  { id: 'congo_kinshasa', name: 'Congo (Kinshasa)', priority: false },
  { id: 'costa_rica', name: 'Costa Rica', priority: false },
  { id: 'croatia', name: 'Croatia', priority: false },
  { id: 'cuba', name: 'Cuba', priority: false },
  { id: 'cyprus', name: 'Cyprus', priority: false },
  { id: 'czech_republic', name: 'Czech Republic', priority: false },
  { id: 'denmark', name: 'Denmark', priority: false },
  { id: 'djibouti', name: 'Djibouti', priority: false },
  { id: 'dominica', name: 'Dominica', priority: false },
  { id: 'dominican_republic', name: 'Dominican Republic', priority: false },
  { id: 'ecuador', name: 'Ecuador', priority: false },
  { id: 'egypt', name: 'Egypt', priority: false },
  { id: 'el_salvador', name: 'El Salvador', priority: false },
  { id: 'equatorial_guinea', name: 'Equatorial Guinea', priority: false },
  { id: 'eritrea', name: 'Eritrea', priority: false },
  { id: 'estonia', name: 'Estonia', priority: false },
  { id: 'eswatini', name: 'Eswatini', priority: false },
  { id: 'ethiopia', name: 'Ethiopia', priority: false },
  { id: 'fiji', name: 'Fiji', priority: false },
  { id: 'finland', name: 'Finland', priority: false },
  { id: 'france', name: 'France', priority: false },
  { id: 'gabon', name: 'Gabon', priority: false },
  { id: 'gambia', name: 'Gambia', priority: false },
  { id: 'georgia', name: 'Georgia', priority: false },
  { id: 'germany', name: 'Germany', priority: false },
  { id: 'ghana', name: 'Ghana', priority: false },
  { id: 'greece', name: 'Greece', priority: false },
  { id: 'grenada', name: 'Grenada', priority: false },
  { id: 'guatemala', name: 'Guatemala', priority: false },
  { id: 'guinea', name: 'Guinea', priority: false },
  { id: 'guinea_bissau', name: 'Guinea-Bissau', priority: false },
  { id: 'guyana', name: 'Guyana', priority: false },
  { id: 'haiti', name: 'Haiti', priority: false },
  { id: 'honduras', name: 'Honduras', priority: false },
  { id: 'hungary', name: 'Hungary', priority: false },
  { id: 'iceland', name: 'Iceland', priority: false },
  { id: 'india', name: 'India', priority: false },
  { id: 'indonesia', name: 'Indonesia', priority: false },
  { id: 'iran', name: 'Iran', priority: false },
  { id: 'iraq', name: 'Iraq', priority: false },
  { id: 'ireland', name: 'Ireland', priority: false },
  { id: 'israel', name: 'Israel', priority: false },
  { id: 'italy', name: 'Italy', priority: false },
  { id: 'ivory_coast', name: 'Ivory Coast', priority: false },
  { id: 'jamaica', name: 'Jamaica', priority: false },
  { id: 'japan', name: 'Japan', priority: false },
  { id: 'jordan', name: 'Jordan', priority: false },
  { id: 'kazakhstan', name: 'Kazakhstan', priority: false },
  { id: 'kenya', name: 'Kenya', priority: false },
  { id: 'kiribati', name: 'Kiribati', priority: false },
  { id: 'kosovo', name: 'Kosovo', priority: false },
  { id: 'kuwait', name: 'Kuwait', priority: false },
  { id: 'kyrgyzstan', name: 'Kyrgyzstan', priority: false },
  { id: 'laos', name: 'Laos', priority: false },
  { id: 'latvia', name: 'Latvia', priority: false },
  { id: 'lebanon', name: 'Lebanon', priority: false },
  { id: 'lesotho', name: 'Lesotho', priority: false },
  { id: 'liberia', name: 'Liberia', priority: false },
  { id: 'libya', name: 'Libya', priority: false },
  { id: 'liechtenstein', name: 'Liechtenstein', priority: false },
  { id: 'lithuania', name: 'Lithuania', priority: false },
  { id: 'luxembourg', name: 'Luxembourg', priority: false },
  { id: 'madagascar', name: 'Madagascar', priority: false },
  { id: 'malawi', name: 'Malawi', priority: false },
  { id: 'malaysia', name: 'Malaysia', priority: false },
  { id: 'maldives', name: 'Maldives', priority: false },
  { id: 'mali', name: 'Mali', priority: false },
  { id: 'malta', name: 'Malta', priority: false },
  { id: 'marshall_islands', name: 'Marshall Islands', priority: false },
  { id: 'mauritania', name: 'Mauritania', priority: false },
  { id: 'mauritius', name: 'Mauritius', priority: false },
  { id: 'mexico', name: 'Mexico', priority: false },
  { id: 'micronesia', name: 'Micronesia', priority: false },
  { id: 'moldova', name: 'Moldova', priority: false },
  { id: 'monaco', name: 'Monaco', priority: false },
  { id: 'montenegro', name: 'Montenegro', priority: false },
  { id: 'morocco', name: 'Morocco', priority: false },
  { id: 'mozambique', name: 'Mozambique', priority: false },
  { id: 'myanmar', name: 'Myanmar', priority: false },
  { id: 'namibia', name: 'Namibia', priority: false },
  { id: 'nauru', name: 'Nauru', priority: false },
  { id: 'nepal', name: 'Nepal', priority: false },
  { id: 'netherlands', name: 'Netherlands', priority: false },
  { id: 'new_zealand', name: 'New Zealand', priority: false },
  { id: 'nicaragua', name: 'Nicaragua', priority: false },
  { id: 'niger', name: 'Niger', priority: false },
  { id: 'nigeria', name: 'Nigeria', priority: false },
  { id: 'north_korea', name: 'North Korea', priority: false },
  { id: 'north_macedonia', name: 'North Macedonia', priority: false },
  { id: 'norway', name: 'Norway', priority: false },
  { id: 'oman', name: 'Oman', priority: false },
  { id: 'pakistan', name: 'Pakistan', priority: false },
  { id: 'palau', name: 'Palau', priority: false },
  { id: 'palestine', name: 'Palestine', priority: false },
  { id: 'panama', name: 'Panama', priority: false },
  { id: 'papua_new_guinea', name: 'Papua New Guinea', priority: false },
  { id: 'paraguay', name: 'Paraguay', priority: false },
  { id: 'peru', name: 'Peru', priority: false },
  { id: 'philippines', name: 'Philippines', priority: false },
  { id: 'poland', name: 'Poland', priority: false },
  { id: 'portugal', name: 'Portugal', priority: false },
  { id: 'qatar', name: 'Qatar', priority: false },
  { id: 'romania', name: 'Romania', priority: false },
  { id: 'russia', name: 'Russia', priority: false },
  { id: 'rwanda', name: 'Rwanda', priority: false },
  { id: 'saint_kitts_and_nevis', name: 'Saint Kitts and Nevis', priority: false },
  { id: 'saint_lucia', name: 'Saint Lucia', priority: false },
  { id: 'saint_vincent_and_the_grenadines', name: 'Saint Vincent and the Grenadines', priority: false },
  { id: 'samoa', name: 'Samoa', priority: false },
  { id: 'san_marino', name: 'San Marino', priority: false },
  { id: 'sao_tome_and_principe', name: 'Sao Tome and Principe', priority: false },
  { id: 'saudi_arabia', name: 'Saudi Arabia', priority: false },
  { id: 'senegal', name: 'Senegal', priority: false },
  { id: 'serbia', name: 'Serbia', priority: false },
  { id: 'seychelles', name: 'Seychelles', priority: false },
  { id: 'sierra_leone', name: 'Sierra Leone', priority: false },
  { id: 'singapore', name: 'Singapore', priority: false },
  { id: 'slovakia', name: 'Slovakia', priority: false },
  { id: 'slovenia', name: 'Slovenia', priority: false },
  { id: 'solomon_islands', name: 'Solomon Islands', priority: false },
  { id: 'somalia', name: 'Somalia', priority: false },
  { id: 'south_africa', name: 'South Africa', priority: false },
  { id: 'south_korea', name: 'South Korea', priority: false },
  { id: 'south_sudan', name: 'South Sudan', priority: false },
  { id: 'spain', name: 'Spain', priority: false },
  { id: 'sri_lanka', name: 'Sri Lanka', priority: false },
  { id: 'sudan', name: 'Sudan', priority: false },
  { id: 'suriname', name: 'Suriname', priority: false },
  { id: 'sweden', name: 'Sweden', priority: false },
  { id: 'switzerland', name: 'Switzerland', priority: false },
  { id: 'syria', name: 'Syria', priority: false },
  { id: 'taiwan', name: 'Taiwan', priority: false },
  { id: 'tajikistan', name: 'Tajikistan', priority: false },
  { id: 'tanzania', name: 'Tanzania', priority: false },
  { id: 'thailand', name: 'Thailand', priority: false },
  { id: 'timor_leste', name: 'Timor-Leste', priority: false },
  { id: 'togo', name: 'Togo', priority: false },
  { id: 'tonga', name: 'Tonga', priority: false },
  { id: 'trinidad_and_tobago', name: 'Trinidad and Tobago', priority: false },
  { id: 'tunisia', name: 'Tunisia', priority: false },
  { id: 'turkmenistan', name: 'Turkmenistan', priority: false },
  { id: 'tuvalu', name: 'Tuvalu', priority: false },
  { id: 'uganda', name: 'Uganda', priority: false },
  { id: 'ukraine', name: 'Ukraine', priority: false },
  { id: 'united_arab_emirates', name: 'United Arab Emirates', priority: false },
  { id: 'united_kingdom', name: 'United Kingdom', priority: false },
  { id: 'uruguay', name: 'Uruguay', priority: false },
  { id: 'vanuatu', name: 'Vanuatu', priority: false },
  { id: 'vatican_city', name: 'Vatican City', priority: false },
  { id: 'venezuela', name: 'Venezuela', priority: false },
  { id: 'yemen', name: 'Yemen', priority: false },
  { id: 'zambia', name: 'Zambia', priority: false },
  { id: 'zimbabwe', name: 'Zimbabwe', priority: false },
];

// Combined list: Priority countries first, then all others
export const ALL_COUNTRIES: CountryOption[] = [
  ...PRIORITY_COUNTRIES,
  ...OTHER_COUNTRIES
];

export const PRIORITY_COUNTRY_IDS = PRIORITY_COUNTRIES.map(c => c.id);
